### ISSUE TITLE
Contact attempt

### ISSUE THREAD

**Issue by loganek** [yamt/aloha#1]
Hi Yamamoto,
I hope you're doing well. Sorry for opening a PR here but couldn't find any other method to contact you directly (the email you use for git, netbsd one, seems to be outdated). We're trying to make some improvements around WebAssembly Micro Runtime debugging support and organizing a meeting next week about that. As you're one of the core contributor to that module, we'd like to have you on the call. Could you please contact me directly through email `mkolny <at> amazon.com` so I can share more details? 

Many thanks,
Marcin

**Comment by yamt** [comment]
@loganek i sent you an email from my midokura.com email address.
